name: 'Create major release version'
description: 'Create and configure new major version of new release'
author: 'Nicolas Filippelli'
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
  SETTINGS_FILE:
    description: "Path of the settings file."
    required: true
  VERSION_PREFIX:
    description: "Prefix of the version."
    required: true
  TAG_PREFIX:
    description: "prefix for the versioning"
    required: true
  GIT_USER_EMAIL:
    description: "git author email"
    required: true
  GIT_USER_NAME:
    description: "git author name"
    required: true
  WORKFLOW_FILE:
    description: "Path of the workflow file."
    required: true
  VERSION_FILE:
    description: "Path of the version file."
    required: true
  SCRIPTS_PATH:
    description: "Path of the scripts files."
    required: true
  ASSIGN_PROJECT_FILE:
    description: "Path of the assign project workflow file."
    required: true
  ARCHIVE_CONFIG_FILE:
    description: "Path of the archive config file."
    required: true
  JIRA_SUBDOMAIN:
    description: "subdomain to jira cloud"
    required: true
  JIRA_USER:
    description: "username for jira cloud"
    required: true
  JIRA_TOKEN:
    description: "token for jira cloud"
    required: true
  JIRA_PROJECTS_IDS:
    description: "projects ids from jira cloud. list comma separated"
    required: true
  JIRA_PROJECTS_KEYS:
    description: "projects keys from jira cloud. list comma separated"
    required: true
  JIRA_MASTER_PROJECT_ID:
    description: "master project id from jira cloud"
    required: true
  JIRA_MASTER_PROJECT_KEY:
    description: "master project key jira cloud"
    required: true
  JIRA_MASTER_ISSUE_TYPE:
    description: "master issue type id from jira cloud"
    required: true
  CONFLUENCE_ANCESTOR:
    description: "ancestor id from confluence cloud"
    required: true
  CONFLUENCE_SPACE:
    description: "space key from confluence cloud"
    required: true
  CONFLUENCE_CONTENT_FILE:
    description: "content file path for the confluence cloud page"
    required: true
outputs:
  RELEASE_INFO:
    description: "Information about created release version."
runs:
  using: 'node12'
  main: 'dist/index.js'
