name: 'Create major release version'
description: 'Create and configure new major version of new release'
author: 'Nicolas Filippelli'
inputs:
  GITHUB_TOKEN:
    description: "User token of service account."
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
